<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Puja-DESKTOP-RHKM7B4" name="firefox" tests="3" failures="1" timestamp="2 Apr 2023 11:19:28 GMT" time="20.219" errors="0">
  <testcase name="InvalidLogin" time="0.727" classname="TestsScripts.InvalidLoginTest">
    <failure type="java.lang.AssertionError" message="LoginUrl Validation Failed expected [https://www.saucedemo1.com/] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: LoginUrl Validation Failed expected [https://www.saucedemo1.com/] but found [https://www.saucedemo.com/]
	at TestsScripts.InvalidLoginTest.InvalidLogin(InvalidLoginTest.java:19)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- InvalidLogin -->
  <testcase name="ValidLogin" time="0.573" classname="TestsScripts.ValidLoginTest"/>
  <testcase name="validateThanksMessage" time="1.581" classname="TestsScripts.ValidLoginTest"/>
</testsuite> <!-- firefox -->
